name: Accessible Radiobutton
author: mashalla
category: Widgets
tags: [radiobutton, button]
#docs: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
demo: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
current: 1.2